"""
Seed bias auditing.

Validates that no exact keyword appears more than KEYWORD_CAP times in any
seed file. Writes warnings to reports/seed_bias_warnings.md but does NOT
block execution — bias is a warning, not an error.

Used by: 13_bias_audit.py, 01_generate_queries.py (warning-only).
"""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
WARNINGS_FILE = ROOT / "reports" / "seed_bias_warnings.md"

KEYWORD_CAP = 3
HEALTHCARE_KEYWORDS = ["clinical", "health", "medical", "patient", "ehr", "guideline",
                       "icu", "discharge", "medqa", "pubmed"]
LLM_EVAL_KEYWORDS = ["llm judge", "llm-as-a-judge", "llm evaluation",
                     "evaluation methodology", "benchmark variance"]
ARTIFACT_TARGETS = ["dataset", "benchmark", "tool", "database", "framework"]


def _split_keywords(s: str) -> list[str]:
    return [k.strip().lower() for k in s.replace("|", ";").split(";") if k.strip()]


def audit_seed_file(path: Path) -> dict[str, Any]:
    """Returns audit data: keyword counts, healthcare share, LLM-eval share,
    artifact share, repeated-keyword warnings."""
    if not path.exists():
        return {"path": str(path), "error": "missing"}

    rows = list(csv.DictReader(path.open(encoding="utf-8")))
    n = len(rows)
    if n == 0:
        return {"path": str(path), "n_topics": 0, "warnings": []}

    keyword_counter: Counter = Counter()
    keyword_topics: dict[str, list[str]] = defaultdict(list)

    for r in rows:
        tid = r.get("topic_id", "?")
        for k in _split_keywords(r.get("keywords", "")):
            keyword_counter[k] += 1
            keyword_topics[k].append(tid)

    # Repeated-keyword warnings
    repeated: list[dict[str, Any]] = []
    for kw, count in keyword_counter.most_common():
        if count > KEYWORD_CAP:
            risk = ""
            if any(t in kw for t in HEALTHCARE_KEYWORDS):
                risk = "healthcare overrepresentation"
            elif any(t in kw for t in [k.lower() for k in LLM_EVAL_KEYWORDS]):
                risk = "LLM-eval anchoring"
            elif kw in ARTIFACT_TARGETS:
                risk = "artifact-type bias"
            else:
                risk = "keyword-cluster overrepresentation"

            repeated.append({
                "keyword":     kw,
                "count":       count,
                "topic_ids":   keyword_topics[kw],
                "risk":        risk,
                "recommendation": (f"Reduce occurrences of '{kw}' to <= {KEYWORD_CAP}; "
                                   f"diversify by replacing duplicates with related but distinct keywords."),
            })

    # Category counts
    n_health = sum(1 for r in rows
                   if "health" in r.get("category", "").lower()
                   or "clinical" in r.get("category", "").lower())
    n_llm    = sum(1 for r in rows
                   if any(w in r.get("keywords", "").lower()
                          for w in [k.lower() for k in LLM_EVAL_KEYWORDS]))
    n_art    = sum(1 for r in rows
                   if any(w in r.get("target_artifact", "").lower()
                          for w in ARTIFACT_TARGETS))
    n_nc     = sum(1 for r in rows
                   if (r.get("is_negative_control", "").lower() in ("true", "1", "yes"))
                   or "[negative_control]" in r.get("title", "").lower())

    return {
        "path":             str(path),
        "n_topics":         n,
        "n_healthcare":     n_health,
        "healthcare_pct":   round(100 * n_health / n, 1),
        "n_llm_eval":       n_llm,
        "llm_eval_pct":     round(100 * n_llm / n, 1),
        "n_artifact":       n_art,
        "artifact_pct":     round(100 * n_art / n, 1),
        "n_negative_control": n_nc,
        "repeated_keywords": repeated,
        "warnings":         [r for r in repeated],
    }


def write_warnings_report(audits: list[dict[str, Any]]) -> Path:
    """Write reports/seed_bias_warnings.md aggregating audits across seed files."""
    WARNINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Seed Bias Warnings", "",
             "_Generated by `scripts/common/seed_audit.py` "
             f"(KEYWORD_CAP={KEYWORD_CAP})._", ""]

    any_warnings = False
    for a in audits:
        lines.append(f"## {a.get('path', 'unknown')}")
        lines.append("")
        if a.get("error"):
            lines.append(f"_Error_: {a['error']}")
            lines.append("")
            continue
        lines.append(f"- topics: **{a['n_topics']}**")
        lines.append(f"- healthcare-tagged: {a['n_healthcare']} ({a['healthcare_pct']}%)")
        lines.append(f"- LLM-eval-keyword-tagged: {a['n_llm_eval']} ({a['llm_eval_pct']}%)")
        lines.append(f"- artifact-target tagged: {a['n_artifact']} ({a['artifact_pct']}%)")
        lines.append(f"- negative-control topics: {a['n_negative_control']}")
        lines.append("")

        rep = a.get("repeated_keywords", [])
        if rep:
            any_warnings = True
            lines.append(f"### WARNING: {len(rep)} keyword(s) exceed cap ({KEYWORD_CAP})")
            lines.append("")
            lines.append("| keyword | count | topic_ids | risk | recommendation |")
            lines.append("|---|---|---|---|---|")
            for r in rep:
                tids = ", ".join(r["topic_ids"][:6]) + (" ..." if len(r["topic_ids"]) > 6 else "")
                lines.append(f"| `{r['keyword']}` | {r['count']} | {tids} | "
                             f"{r['risk']} | {r['recommendation']} |")
            lines.append("")
        else:
            lines.append("_No keywords exceed the cap._")
            lines.append("")

    if not any_warnings:
        lines.append("---")
        lines.append("_No bias warnings across audited seeds._")

    WARNINGS_FILE.write_text("\n".join(lines), encoding="utf-8")
    return WARNINGS_FILE


def audit_all_default_seeds() -> list[dict[str, Any]]:
    """Audit the standard set of seed files. Returns audits + writes warnings report."""
    seed_files = [
        ROOT / "data" / "topics_seed.csv",
        ROOT / "data" / "topics_seed_full_75.csv",
        ROOT / "data" / "topics_seed_balanced.csv",
    ]
    audits = [audit_seed_file(p) for p in seed_files if p.exists()]
    write_warnings_report(audits)
    return audits


if __name__ == "__main__":
    audits = audit_all_default_seeds()
    import json
    print(json.dumps(audits, indent=2))
    print(f"\nWarnings written to {WARNINGS_FILE}")
